/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-error': '#690005',
        'primary-fixed': '#e5e2e1',
        tertiary: '#ffb59f',
        'surface-container-highest': '#333535',
        'secondary-fixed-dim': '#c8c6c6',
        'on-secondary-container': '#b9b8b8',
        error: '#ffb4ab',
        'inverse-on-surface': '#2f3131',
        'on-background': '#e2e2e2',
        'primary-fixed-dim': '#c8c6c5',
        'on-secondary': '#303030',
        background: '#121414',
        'on-surface-variant': '#c1c6d5',
        'surface-tint': '#c8c6c5',
        'error-container': '#93000a',
        'on-surface': '#e2e2e2',
        'on-primary-fixed': '#1c1b1b',
        outline: '#8b919f',
        'inverse-surface': '#e2e2e2',
        'on-secondary-fixed-variant': '#474747',
        'on-secondary-fixed': '#1b1c1c',
        'inverse-primary': '#5f5e5e',
        secondary: '#c8c6c6',
        'tertiary-fixed-dim': '#ffb59f',
        'on-tertiary': '#5f1600',
        'on-primary-fixed-variant': '#474746',
        'surface-container-lowest': '#0d0e0f',
        'tertiary-container': '#fa5c29',
        'secondary-fixed': '#e4e2e2',
        'surface-container-low': '#1a1c1c',
        surface: '#121414',
        'on-primary': '#313030',
        'surface-dim': '#121414',
        'tertiary-fixed': '#ffdbd1',
        'on-tertiary-fixed-variant': '#862300',
        'on-error-container': '#ffdad6',
        'outline-variant': '#414753',
        'secondary-container': '#494949',
        'on-tertiary-fixed': '#3a0a00',
        primary: '#c8c6c5',
        'surface-container-high': '#282a2b',
        'surface-container': '#1e2020',
        'surface-bright': '#38393a',
        'on-primary-container': '#2a2a2a',
        'on-tertiary-container': '#531200',
        'primary-container': '#929090',
        'surface-variant': '#333535',
        'status-healthy': '#4ade80',
        'status-degraded': '#fbbf24',
        'status-major': '#f97316',
        'status-critical': '#f87171',
        'theme-orange': '#fa5c29',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        md: '16px',
        base: '8px',
        gutter: '16px',
        sm: '8px',
        xs: '4px',
        xl: '32px',
        lg: '24px',
        'margin-page': '32px',
        'container-max': '1280px',
      },
      fontFamily: {
        'body-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-md': ['DM Sans', 'sans-serif'],
        'headline-lg': ['DM Sans', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '1.25', fontWeight: '600' }],
        'headline-lg': ['40px', { lineHeight: '1.2', fontWeight: '700' }],
        'label-md': ['14px', { lineHeight: '1.4', letterSpacing: '0.02em', fontWeight: '500' }],
      },
      boxShadow: {
        'glow-healthy': '0 0 8px rgba(74, 222, 128, 0.4)',
        'glow-degraded': '0 0 8px rgba(251, 191, 36, 0.4)',
        'glow-major': '0 0 8px rgba(249, 115, 22, 0.4)',
        'glow-critical': '0 0 8px rgba(248, 113, 113, 0.4)',
        'glow-orange': '0 0 12px rgba(250, 92, 41, 0.3)',
      },
    },
  },
  plugins: [],
}